### ISSUE TITLE
[HELP] how to configure dialog which has multiple tabs.

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#203]
Dialog was created with multiple tabs, 

<img width="262" alt="screen shot 2017-06-22 at 7 48 04 pm" src="https://user-images.githubusercontent.com/6211294/27464725-c1476884-5783-11e7-9394-3bfb752676da.png">

Not able to read the yaml.

```
demo:
  Componet:
     TabOne:
        type: TEXTFIELD
        label: label One
         value: Demo 1
```

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish,

the structure of component configuration have to be in the following format:
```
<config-name>:
    <tab-name>:
        - type: <field-type>
          label: <field-label>
          value: <field-value>
        - ...
    <tab-name>:
        - ...
    ...
```
Please note the indentation (YAML structure is determined by it) and the dash sign (which indicates an array element). 
Based on the above, your config should look like:
```
ttl_demo:
    General/Title:
        - ...
    Links:
        - ...
    ...
```
