### ISSUE TITLE
[HELP]Sample YAML file for configuring Multifield in Custom Dialog fields

### ISSUE THREAD

**Issue by purubarh** [Cognifide/bobcat#221]
@CognifideLabs @mmajchrzak 
I am trying to configure the multifield available in custom dialog fields. Can you please provide sample YAML file for configuring Multifield in Custom Dialog fields.

![image](https://user-images.githubusercontent.com/15006279/35375267-4bc002d8-015b-11e8-918c-4bf64d8a4fa4.png)

Once click on Add field on attached Mutiple fields open up. Would like to configure all the field by componentconfiguration function available in wiki. can you please suggest how to write YAML file for Multifield.

**Comment by mkrzyzanowski** [comment]
Sample YAML is included in wiki over here: https://github.com/Cognifide/bobcat/wiki/Component-configurer#complex-fields

```
TabName:
    - label: Multifield name
      type: MULTIFIELD
      value:
        - item:
            - label: Example Name
              type: TEXTFIELD
              value: slide1
        - item:
            - label: Example Name
              type: TEXTFIELD
              value: slide2
        - item:
            - label: Example Name
              type: TEXTFIELD
              value: slide3
```

**Comment by purubarh** [comment]
@mkrzyzanowski , Thanks for your reply. I have tried and written the YAML File in same way as mentioned above which is as follows:

- label: Carousel List
      type: MULTIFIELD
      value:
        - item:
          - label: Image
            type: PATHBROWSER
            value: http://www.google.com
        - item:
          - label: Alt Text
            type: TEXTFIELD
            value: Image Alt Text
        - item:
          - label: Title
            type: TEXTFIELD
            value: Title 

![image](https://user-images.githubusercontent.com/15006279/35583235-18b57a54-05a6-11e8-848f-044066fb4a68.png)

Once Click on add field , it is opening multifiled dialog with multiple fields.
![image](https://user-images.githubusercontent.com/15006279/35583281-3ec2acd0-05a6-11e8-81e7-dd8792697a72.png)

With the YAML file mentioned above, I am only able to configure first field available after clicking on Add Field. For other fields, it is not able to find other fields and throwing error:

org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".coral-Textfield:not([type='hidden']"}
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.04 seconds

Can you please help me to understand why 2nd field Alt Text is not being traced as TEXTFIELD.

**Comment by mkrzyzanowski** [comment]
In your YAML you are trying to configure 3 fields in separate Multifield items, while in fact, you want to do it in a single one (at least from what I see on the screenshot). Try the following config:

```
- label: Carousel List
      type: MULTIFIELD
      value:
        - item:
          - label: Image
            type: PATHBROWSER
            value: http://www.google.com
          - label: Alt Text
            type: TEXTFIELD
            value: Image Alt Text
          - label: Title
            type: TEXTFIELD
            value: Title 
```

Rinse and repeat for more Multifield items :).
