### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by discovermoi** [Cognifide/bobcat#241]
Local

Bobcat version: 1.3.

Bobcat modules used:
* bb-aem-touch-ui

Browser + version: Chrome Latest

![image](https://user-images.githubusercontent.com/26506371/39568822-98df5ff6-4f02-11e8-87be-0ea90ca3f878.png)

![image](https://user-images.githubusercontent.com/26506371/39569094-5856e750-4f03-11e8-9c6d-57bfc7f18331.png)

![image](https://user-images.githubusercontent.com/26506371/39568833-a1f6a0f4-4f02-11e8-98e9-9f9170adba23.png)

**Comment by mkrzyzanowski** [comment]
Hi @discovermoi,

please provide full information next time (steps to reproduce, stacktraces, etc.).
From what I see, your YAML is not valid:
- you have:
```
HL:
  HEADER:
    - type:: SELECT
       label: Text Position
       value: Centre
       
       type: TEXTFIELD
       label: Page Header
       value: test test test
```
- it should be:
```
HL:
  HEADER:
    - type:: SELECT
       label: Text Position
       value: Centre
       
    -  type: TEXTFIELD
       label: Page Header
       value: test test test
```
